import { ImageSourcePropType } from "react-native";

export type images = {
  authBg: ImageSourcePropType;
  line: ImageSourcePropType;
  offerBg: ImageSourcePropType;
  homeBanner: ImageSourcePropType;
  bellNotification: ImageSourcePropType;
  homeBannerTwo: ImageSourcePropType;
  user: ImageSourcePropType;
  profileUser: ImageSourcePropType;
  promoCodeBg: ImageSourcePropType;
  rideDetail: ImageSourcePropType;
  outStation: ImageSourcePropType;
  rideBg: ImageSourcePropType;
  rental: ImageSourcePropType;
  alto: ImageSourcePropType;
  rangeRover: ImageSourcePropType;
  rangeRoverOne: ImageSourcePropType;
  rangeRoverTwo: ImageSourcePropType;
  taxi: ImageSourcePropType;
  destination: ImageSourcePropType;
  bgOnboarding: ImageSourcePropType;
  bookRide: ImageSourcePropType;
  bookRideDark: ImageSourcePropType;
  trip: ImageSourcePropType;
  tripDark: ImageSourcePropType;
  auto: ImageSourcePropType;
  bike: ImageSourcePropType;
  carTwo: ImageSourcePropType;
  freight: ImageSourcePropType;
  parcel: ImageSourcePropType;
  verticalLine: ImageSourcePropType;
  categoryTwo: ImageSourcePropType;
  promoCodeList: ImageSourcePropType;
  offerBgDark: ImageSourcePropType;
  rideDetailDark: ImageSourcePropType;
  destinationDark: ImageSourcePropType;
  bgDarkOnboard: ImageSourcePropType;
  authBgDark: ImageSourcePropType;
  mapEngland: ImageSourcePropType;
  french: ImageSourcePropType;
  spanish: ImageSourcePropType;
  arabic: ImageSourcePropType;
  euro: ImageSourcePropType;
  dollar: ImageSourcePropType;
  rs: ImageSourcePropType;
  english: ImageSourcePropType;
  splash: ImageSourcePropType;
  splashDark: ImageSourcePropType;
  googlePay: ImageSourcePropType;
  creditCard: ImageSourcePropType;
  paypal: ImageSourcePropType;
  cash: ImageSourcePropType;
  lineBottom: ImageSourcePropType;
  line2: ImageSourcePropType;
  walletBg: ImageSourcePropType;
  carPrime: ImageSourcePropType;
  rideLogo: ImageSourcePropType;
  outstationLogo: ImageSourcePropType;
  rentalLogo: ImageSourcePropType;
  scheduledLogo: ImageSourcePropType;
  scheduled: ImageSourcePropType;
  pin: ImageSourcePropType;
  car: ImageSourcePropType;
  notFound: ImageSourcePropType;
  noInternet: ImageSourcePropType;
  maintenance: ImageSourcePropType;
  noLocation: ImageSourcePropType;
  noServices: ImageSourcePropType;
  noBalance: ImageSourcePropType;
  discount: ImageSourcePropType;
  or: ImageSourcePropType;
  otpVerify: ImageSourcePropType;
  noVehicle: ImageSourcePropType;
  noOffer: ImageSourcePropType;
  noService: ImageSourcePropType;
  defultImage: ImageSourcePropType;
  noRide: ImageSourcePropType;
  noTicket: ImageSourcePropType;
  activeRideGo: ImageSourcePropType;
  splashBg: ImageSourcePropType;
  loaderGIF: ImageSourcePropType;
  noTicketDark: ImageSourcePropType;
  noLocationDark: ImageSourcePropType;
  noBalanceDark: ImageSourcePropType;
  noVehicleDark: ImageSourcePropType;
  noOfferDark: ImageSourcePropType;
  noServiceDark: ImageSourcePropType;
  maintenanceDark: ImageSourcePropType;
  noRideDark: ImageSourcePropType;
  noInternetDark: ImageSourcePropType;
  darkLine: ImageSourcePropType;
  noSignin: ImageSourcePropType;
  noSigninDark: ImageSourcePropType;
  otpDark:ImageSourcePropType;
};

const Images: images = {
  authBg: require("@assets/images/authImage/authBg.png"),
  otpDark:require("@assets/images/authImage/otpDark.png"),
  line: require("@assets/images/gif/line.gif"),
  noService: require("@assets/images/gif/noService.gif"),
  bellNotification: require("@assets/images/notification/bellNotification.png"),
  offerBg: require("@assets/images/homeScreenImage/offerBg.png"),
  rideLogo: require("@assets/images/homeScreenImage/rideLogo.png"),
  homeBanner: require("@assets/images/homeScreenImage/homeBanner.png"),
  homeBannerTwo: require("@assets/images/homeScreenImage/homeBannerTwo.png"),
  user: require("@assets/images/homeScreenImage/user.png"),
  profileUser: require("@assets/images/profileImage/profileUser.png"),
  promoCodeBg: require("@assets/images/profileTab/promoCode.png"),
  rideDetail: require("@assets/images/rideScreen/rideDetail.png"),
  outStation: require("@assets/images/categoryScreen/outstation.png"),
  rideBg: require("@assets/images/categoryScreen/rideBg.png"),
  rental: require("@assets/images/categoryScreen/rental.png"),
  scheduled: require("@assets/images/categoryScreen/Scheduled.png"),
  destination: require("@assets/images/onBoarding/destination.png"),
  bgOnboarding: require("@assets/images/onBoarding/bgOnboarding.png"),
  bookRide: require("@assets/images/onBoarding/bookRide.png"),
  bookRideDark: require("@assets/images/onBoarding/bookRideDark.png"),
  trip: require("@assets/images/onBoarding/trip.png"),
  tripDark: require("@assets/images/onBoarding/tripDark.png"),
  freight: require("@assets/images/outStation/freight.png"),
  parcel: require("@assets/images/outStation/parcel.png"),
  verticalLine: require("@assets/images/outStation/verticalLine.png"),
  categoryTwo: require("@assets/images/homeScreenImage/categoryTwo.png"),
  promoCodeList: require("@assets/images/profileImage/promoCodeList.png"),
  offerBgDark: require("@assets/images/homeScreenImage/offerBgDark.png"),
  rideDetailDark: require("@assets/images/rideScreen/rideDetailDark.png"),
  destinationDark: require("@assets/images/onBoarding/destinationDark.png"),
  bgDarkOnboard: require("@assets/images/onBoarding/bgDarkOnboard.png"),
  authBgDark: require("@assets/images/authImage/authBgDark.png"),
  mapEngland: require("@assets/images/language/english.png"),
  english: require("@assets/images/language/englishLang.png"),
  french: require("@assets/images/language/french.png"),
  spanish: require("@assets/images/language/spanish.png"),
  arabic: require("@assets/images/language/arabic.png"),
  splash: require("@assets/images/splash/splash.png"),
  splashDark: require("@assets/images/splash/splashDark.png"),
  cash: require("@assets/images/payment/cash.png"),
  lineBottom: require("@assets/images/line.png"),
  line2: require("@assets/images/line2.png"),
  outstationLogo: require("@assets/images/homeScreenImage/outstationLogo.png"),
  walletBg: require("@assets/images/walletBg.png"),
  rentalLogo: require("@assets/images/homeScreenImage/rentalLogo.png"),
  scheduledLogo: require("@assets/images/homeScreenImage/scheduledLogo.png"),
  pin: require("@assets/images/map/pin.png"),
  car: require("@assets/images/map/car.png"),
  notFound: require("@assets/images/noData/notFound.png"),
  noInternet: require("@assets/images/noInternet/noInternet.png"),
  maintenance: require("@assets/images/noInternet/maintenance.png"),
  noLocation: require("@assets/images/noInternet/noLocation.png"),
  noServices: require("@assets/images/noInternet/noService.png"),
  noBalance: require("@assets/images/noInternet/noBalance.png"),
  discount: require("@assets/images/discount/discount.png"),
  or: require("@assets/images/or.png"),
  otpVerify: require("@assets/images/authImage/otp.png"),
  noVehicle: require("@assets/images/noInternet/noVehicle.png"),
  noOffer: require("@assets/images/noInternet/noOffer.png"),
  defultImage: require("@assets/images/profileImage/defultImage.png"),
  noRide: require("@assets/images/noInternet/noRide.png"),
  noTicket: require("@assets/images/noInternet/noTicket.png"),
  activeRideGo: require("@assets/images/gif/activeRideGo.gif"),
  splashBg: require("@assets/images/splash/splashBg.png"),
  loaderGIF: require("@assets/images/gif/loader.gif"),
  noTicketDark: require("@assets/images/noInternet/noTicketDark.png"),
  noLocationDark: require("@assets/images/noInternet/noLocationDark.png"),
  noBalanceDark: require("@assets/images/noInternet/noBalanceDark.png"),
  noVehicleDark: require("@assets/images/noInternet/noVehicleDark.png"),
  noOfferDark: require("@assets/images/noInternet/noOfferDark.png"),
  noServiceDark: require("@assets/images/noInternet/noServiceDark.png"),
  maintenanceDark: require("@assets/images/noInternet/maintenanceDark.png"),
  noRideDark: require("@assets/images/noInternet/noRideDark.png"),
  noInternetDark: require("@assets/images/noInternet/noInternetDark.png"),
  darkLine: require("@assets/images/gif/darkLine.gif"),
  noSignin: require("@assets/images/noInternet/noSignin.png"),
  noSigninDark: require("@assets/images/noInternet/noSigninDark.png"),
  paypal:require("@assets/images/payment/payPal.png"),
  creditCard:require("@assets/images/payment/creditCard.png"),
  googlePay:require("@assets/images/payment/googlePay.png")
};
export default Images;
